// Copyright (c) 2025 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: jakarta-concurrency
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2025-06-30
:page-description: Learn how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency.
:guide-author: Open Liberty
:page-tags: ['jakarta-ee']
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-related-guides: ['reactive-rest-client', 'microprofile-rest-client-async, 'reactive-messaging-sse']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Running tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency APIs
:page-seo-description: A getting started tutorial with examples on how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency APIs.
= Running tasks parallelly or asynchronously in Java microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency.

== What you'll learn

Jakarta Concurrency enables the creation of managed executors to run concurrent and asynchronous tasks in different threads. It also enables the creation of managed thread factories to create threads that run with the thread context of the component that looks up the managed thread factory. The threads are managed by the application server, coexist and safely interact in the Enterprise Java Beans and Web containers. To learn more about Jakarta Concurrency, see the https://jakarta.ee/specifications/concurrency[Jakarta Concurrency specification^].

The application in this guide provides GET REST APIs to retrieve the Java system properties parallelly and calculate the system load asynchronously. Also, you can toggle the schedule to retreive the latest system load.

You'll learn how to run tasks in parallel by enhancing the GET `/api/system/properties/{prefix}` endpoint, create asynchronous task by the GET `/api/system/systemLoad/{after}` endpoint that updates the system load after the provided `{after}` seconds, and schedule a task to retreive the latest the system load for every 10 seconds.

// =================================================================================================
// Getting started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Go to the http://localhost:9080/api/system/properties/os URL to see all the `os.*` properties. You will see an output similar to the following:

[role="no_copy"]
----
{
  "os.arch": "aarch64",
  "os.name": "Mac OS X",
  "os.version": "15.4.1",
  "os.encoding": "UTF-8"
}
----

If you interest, you can check out the endpoint by the http://localhost:9080/api/system/properties/user and http://localhost:9080/api/system/properties/java URLs.

Check out the web application at the http://localhost:9080 URL. Click the image:refresh.svg[refresh icon, 20, 20] refresh button, located in the table title, to update and display the latest system load data in the table after 5 seconds.

Click the image:schedule.svg[schedule icon, 20, 20] schedule button to toggle the schedule that posts the latest system load data in every 10 seconds.

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Running tasks in parallel

Navigate to the `start` directory to begin.
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-jakarta-concurrency/start
```
endif::[]

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

// file 0
SystemResource.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

// file 1
start/SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

// file 2
server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The starting application is implemented the [hotspot=getProperties file=0]`/properties/{prefix}` endpoint. Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes several seconds to get the result. Each [hotspot=doSomethingSleep hotspot=getSystemPropertyTask hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` call takes at most a second.

To improve the performance, enhance the [hotspot=getProperties file=1]`getProperties()` method to call the [hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` method in parallel.

// TODO: replace the concurrent-3.0.html to concurrent-3.1.html
The https://openliberty.io/docs/latest/reference/feature/concurrent-3.0.html[Jakarta Concurrency^] feature is enabled for you in the Liberty [hotspot=concurrent file=2]`server.xml` configuration file.

// file 3
WithVirtualThreads.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/WithVirtualThreads.java[]
----

[role="code_command hotspot file=3", subs="quotes"]
----
#Create the `WithVirtualThreads.java` file.#
`src/main/java/io/openliberty/guides/system/WithVirtualThreads.java`
----

The [hotspot file=3]`WithVirtualThreads` qualifier annotation class is used to enumerate the required qualifiers for the managed executor service.

The managed executor service provides a way to start asynchronous tasks within an application server environment. It propagates various thread contexts that are relevant to Jakarta EE applications.

// file 4
SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright,subscribe,calculateSystemLoad,getSystemLoad,enableSchedule,schedule"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=4", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

Annotate the [hotspot file=4]`SystemConcurrency` class with the [hotspot=annotateManagedScheduledExecutor file=4]`@ManagedScheduledExecutorDefinition` annotation to provide a managed executor instance that enumerates the `WithVirtualThreads` required qualifiers through the [hotspot=managedScheduledExecutorService file=4]`ManagedScheduledExecutorService` injection point. Set the [hotspot=virtual file=4]`virtual` attribute to true to use virtual thread.

// TODO: replace the javadoc link to jakartaee11
The `@ManagedScheduledExecutorDefinition` annotation and the `ManagedScheduledExecutorService` interface are used in this guide instead of `@ManagedScheduledDefinition` annotation and `ManagedExecutorService` interface, because you will implement a scheduled task in the following section. For more information about these annotations and classes, see the Javadocs for https://openliberty.io/docs/latest/reference/javadoc/liberty-jakartaee10-javadoc.html?path=liberty-jakartaee10-javadoc/jakarta/enterprise/concurrent/package-summary.html[jakarta.enterprise.concurrent^].


Use the [hotspot=virtualManagedExecutor hotspot=submit file=4]`virtualManagedExecutor` instance to submit callable tasks that call the `getSystemPropertyTask()` method to collect different property values parallelly. Each task creates a virtual thread and returns a `Future<String>` object.

Perform a [hotspot=collect file=4]`collect()` mutable reduction operation on the entries of the [hotspot=properties file=4]`properties` map. In the operation, use the [hotspot=get file=4]`get()` method to wait for all threads to complete and to collect the results.

You started the Open Liberty in dev mode at the beginning of this section, so all the changes were automatically picked up.

Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes a second to get the result.

== Creating asynchronous task

Implement an asynchronous task to update the memory usage of the systems in the inventory.

InventoryAsyncTask.java
[source, Java, linenums, role='code_column hide_tags=copyright,updateSystemsUsage,getSystemLoad']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryAsyncTask.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `InventoryAsyncTask.java` file.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryAsyncTask.java`
----

The [hotspot=updateSystemsMemoryUsedMethod file=0]`updateSystemsMemoryUsed()` method uses the [hotspot=systems hotspot=schedule file=0]`managedExecutor` service to schedule multiple tasks that will be delayed with the given [hotspot=parameters hotspot=after file=0]`after` seconds and ran in parallel. Each task calls the client's [hotspot=getMemoryUsed file=0]`getMemoryUsed()` method to retrieve the memory usage, and calls the system's [hotspot=setMemoryUsage file=0]`setMemoryUsed()` method to calculate the memory usage.

Annotate the [hotspot=asynchronous1 file=0]`updateSystemsMemoryUsed()` method with the `@Asynchronous` annotation to make it running asynchronously.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright,updateSystemLoad']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `InventoryResource.java` file.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----

Create the PUT [hotspot=updateMemoryUsed file=1]`/systems/memoryUsed` endpoint that uses the [hotspot=inventoryAsyncTask file=1]`task` bean's [hotspot=updateSystemsMemoryUsed file=1]`updateSystemsMemoryUsed()` method to update the memory usage of all systems in the inventory and returns immediately.

ifndef::cloud-hosted[]
Go to the http://localhost:9081/openapi/ui URL and make a PUT request to the `/api/inventory/systems/memoryUsed` endpoint with the `after` parameter set to `5` seconds. After 5 seconds, go to the http://localhost:9081/api/inventory/systems URL to see that the `memoryUsage` values are updated to nonzero.
endif::[]

ifdef::cloud-hosted[]
Make a PUT request to the `/api/inventory/systems/memoryUsed` endpoint by the following command:

```bash
curl -X PUT http://localhost:9081/api/inventory/systems/memoryUsed?after=5
```

After 5 seconds, go to the `/api/inventory/systems` endpoint again to see that the `memoryUsage` values are updated to nonzero by the following command:

```bash
curl http://localhost:9081/api/inventory/systems | jq
```
endif::[]

== Synchronizing asynchronous tasks

Synchronize asynchronous tasks to update the system load of the systems in the inventory.

InventoryAsyncTask.java
[source, Java, linenums, role='code_column hide_tags=copyright,updateSystemsUsage']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryAsyncTask.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `InventoryAsyncTask.java` file.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryAsyncTask.java`
----
The [hotspot=getSystemLoadMethod file=0]`getSystemLoad()` method calls the client's [hotspot=clientGetSystemLoad file=0]`getSystemLoad()` method to retrieve the system load, and returns the system load in [hotspot=getSystemLoadSignature file=0]`CompletableFuture<Double>` type by using the [hotspot=return file=0]`Asynchronous.Result.complete()` method.

Annotate the [hotspot=asynchronous2 file=0]`getSystemLoad()` method with the `@Asynchronous` annotation to make it running asynchronously.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `InventoryResource.java` file.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----

Create the PUT [hotspot=updateSystemLoad file=1]`/systems/systemLoad` endpoint that multiply calls the [hotspot=inventoryAsyncTask file=1]`task` bean's [hotspot=getSystemLoad file=1]`getSystemLoad()` method to retrieve the system load of all systems in the inventory. When the calls return, the [hotspot=thenAcceptAsync file=1]`thenAcceptAsync()` method processes the returned data with the `CompletableFuture<Double>` type and calls the system's [hotspot=setSystemLoad file=1]`setSystemLoad()` method to store the system load. Exceptions are handled in a callback that is provided to the [hotspot=exceptionally file=1]`exceptionally()` method, which behaves like a catch block. 

A [hotspot=countDownLatch file=1]`CountDownLatch` object is used to track asynchronous requests. The [hotspot=countDown1 hotspot=countDown2 file=1]`countDown()` method is called whenever a request is complete. When the [hotspot=countDownLatch hotspot=countDown1 hotspot=countDown2 file=1]`CountDownLatch` is at zero, it indicates that all asynchronous requests are complete. By using the [hotspot=await file=1]`await()` method of the `CountDownLatch`, the program waits for all the asynchronous requests to be complete. When all asynchronous requests are complete, the program resumes execution with all required data processed.

ifndef::cloud-hosted[]
Go to the http://localhost:9081/openapi/ui URL and make a PUT request to the `/api/inventory/systems/systemLoad` endpoint with the `after` parameter set to `5` seconds. The request takes 5 seconds to complete. Go to the http://localhost:9081/api/inventory/systems URL to see that the `systemLoad` values are updated to nonzero.
endif::[]

ifdef::cloud-hosted[]
Make a PUT request to the `/api/inventory/systems/systemLoad` endpoint by the following command:

```bash
curl -X PUT http://localhost:9081/api/inventory/systems/systemLoad?after=5
```

The request takes 5 seconds to complete.

Go to the `/api/inventory/systems` endpoint to see that the `systemLoad` values are updated to nonzero by the following command:

```bash
curl http://localhost:9081/api/inventory/systems | jq
```
endif::[]


//== Scheduling asynchronous task
//This section will be available when Liberty supports concurrency-3.1 (now is in beta)
//
//* Replace the InventoryAsyncTask
//  * Create a scheduling method that updates the memory usage and system load of all systems in every 20 seconds

== Testing the inventory application

Although you can test your application manually, automated tests make sure consistent code quality by triggering a failure whenever a code change introduces a defect. Now, create integration tests for the `inventory` microservice.

Create a RESTful client interface for the `inventory` microservice.

InventoryResourceClient.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryResourceClient.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `InventoryResourceClient.java` file.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryResourceClient.java`
----

This interface declares [hotspot=listContents file=0]`listContents()`, [hotspot=getSystem file=0]`getSystem()`, [hotspot=addSystemClient file=0]`addSystemClient()`, [hotspot=updateMemoryUsed file=0]`updateMemoryUsed()`, [hotspot=updateSystemLoad file=0]`updateSystemLoad()`, [hotspot=removeSystem file=0]`removeSystem()`, and [hotspot=resetSystems file=0]`resetSystems()` methods for accessing each of the endpoints that are set up to access the `inventory` microservice.

InventoryEndpointIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryEndpointIT.java` file.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java`
----

The [hotspot=testAddSystems file=1]`testAddSystems()` tests the POST `/inventory/system/{hostname}` endpoint and confirms that three systems are added to the inventory.

The [hotspot=testUpdateMemoryUsed file=1]`testUpdateMemoryUsed()` tests the PUT `/inventory/systems/memoryUsed` endpoint and confirms that the memory usage of each system is greater than 0.0.

The [hotspot=testUpdateSystemLoad file=1]`testUpdateSystemLoad()` tests the PUT `/inventory/systems/systemLoad` endpoint and confirms that the system load of each system is greater than 0.0.

The [hotspot=testResetSystems file=1]`testResetSystems()` tests the PUT `/inventory/systems/reset` endpoint and confirms that the memory usage and the system load of each system are 0.0.

The [hotspot=testRemoveSystem file=1]`testRemoveSystem()` tests the DELETE `/inventory/systems/{hostname}` endpoint and confirms that two systems remain in the inventory.

=== Running the tests

Because you started Open Liberty in dev mode, you can run the tests by pressing the `enter/return` key from the command-line session where you started the `inventory` microservice.

If the tests pass, you see a similar output to the following example:

[source, role='no_copy']
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
...
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.62 s -- in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the services, exit dev mode by pressing `CTRL+C` in the command-line sessions where you ran the `system` and `inventory` microservices.

== Great work! You're done!

You just developed tasks that run parallelly or asynchronously in a Java microservice by using Jakarta Concurrency APIs in Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
