// Copyright (c) 2025 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: jakarta-concurrency
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2025-06-30
:page-description: Learn how to run tasks concurrently or asynchronously in Java microservices by using Jakarta Concurrency.
:guide-author: Open Liberty
:page-tags: ['jakarta-ee']
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-related-guides: ['microprofile-rest-client-async, 'reactive-messaging-sse', 'reactive-rest-client']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Running tasks in parallel or asynchronously in Java microservices by using Jakarta Concurrency
:page-seo-description: A getting started tutorial with examples on how to run tasks in parallel or asynchronously in Java microservices by using Jakarta Concurrency.
= Running tasks concurrently or asynchronously in Java microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to run tasks concurrently or asynchronously in Java microservices by using Jakarta Concurrency.

== What you'll learn

Jakarta Concurrency enables the creation of managed executors to run concurrent and asynchronous tasks in different threads. It also enables the creation of managed thread factories to create threads that run with the thread context of the component that looks up the managed thread factory. The threads are managed by the application server, coexist, access server contexts, and safely interact in the Enterprise Java Beans and Web containers. To learn more about Jakarta Concurrency, see the https://jakarta.ee/specifications/concurrency[Jakarta Concurrency specification^].

The application that you'll build provides REST APIs to retrieve system properties and record system loads including CPU load and memory usage to the database.

You'll update the application to learn how to run tasks in parallel by enhancing the GET `/api/system/properties/{prefix}` endpoint that retrieves system properties with the provided prefix. You'll learn two different ways to create asynchronous task by implementing the GET `/api/system/systemLoad/cpuLoad` and `/api/system/systemLoad/memoryUsage` endpoints that calculate the CPU load and memory usage and persist the data to the database. Also, you'll learn how to create a scheduled asynchronous task that calculates and records the current system load to the database for every 10 seconds.


// =================================================================================================
// Getting started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Go to the http://localhost:9080/api/system/properties/os URL to see all the `os.*` properties. You will see an output similar to the following example:

[role="no_copy"]
----
{
  "os.arch": "aarch64",
  "os.name": "Mac OS X",
  "os.version": "15.4.1",
  "os.encoding": "UTF-8"
}
----

If you are interested, you can check out the GET `/api/system/properties/{prefix}` endpoint by the http://localhost:9080/api/system/properties/user and http://localhost:9080/api/system/properties/java URLs.

Check out the application with the http://localhost:9080/api/system/systemLoad/cpuLoad and http://localhost:9080/api/system/systemLoad/memoryUsage URLs. Both requests return to you immediately with a message. After 5 seconds, go to the http://localhost:9080/api/system/systemLoads URL to see all the system loads. You will see an output similar to the following example:

[role="no_copy"]
----
[
  {
    "id": 1,
    "time": "2025-05-06T15:30:06.308192",
    "cpuLoad": 5.074851387343854e-06
  },
  {
    "id": 2,
    "time": "2025-05-06T15:30:08.732892",
    "memoryUsage": 0.7126722484827042
  }
]
----

Go to the http://localhost:9080/api/system/schedule/toggle URL to toggle the schedule that records the current system load in every 10 seconds. After 10 seconds, go to the http://localhost:9080/api/system/systemLoads URL to see all the system loads.

[role="no_copy"]
----
[
  ...
  {
    "id": 3,
    "time": "2025-05-06T15:34:30.001636",
    "cpuLoad": 1.8270538029075587e-06,
    "memoryUsage": 0.6712260656058788
  },
  ...
]
----

[role='command']
include::{common-includes}/twyb-end.adoc[]


== Running tasks in parallel

Navigate to the `start` directory to begin.
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-jakarta-concurrency/start
```
endif::[]

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

// file 0
SystemResource.java
[source,Java,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

// file 1
start/SystemConcurrency.java
[source,Java,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

// file 2
server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The starting application is implemented the [hotspot=getProperties file=0]`/properties/{prefix}` endpoint. Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes several seconds to get the result. Each [hotspot=doSomethingSleep hotspot=getSystemPropertyTask hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` call takes at least a second.

To improve the performance, enhance the [hotspot=getProperties file=1]`getProperties()` method to call the [hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` method in parallel.

// TODO: replace the concurrent-3.0.html to concurrent-3.1.html
The https://openliberty.io/docs/latest/reference/feature/concurrent-3.0.html[Jakarta Concurrency^] feature is enabled for you in the Liberty [hotspot=concurrent file=2]`server.xml` configuration file.

// file 3
WithVirtualThreads.java
[source,Java,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/WithVirtualThreads.java[]
----

[role="code_command hotspot file=3", subs="quotes"]
----
#Create the `WithVirtualThreads.java` file.#
`src/main/java/io/openliberty/guides/system/WithVirtualThreads.java`
----

The [hotspot file=3]`WithVirtualThreads` qualifier annotation class is used to enumerate the required qualifiers for the managed executor service.

The managed executor service provides a way to start asynchronous tasks within an application server environment. It propagates various thread contexts that are relevant to Jakarta EE applications.

// file 4
SystemConcurrency.java
[source,Java,linenums,role="code_column hide_tags=copyright,subscribe,calculateSystemLoad,getCpuLoad,asynchronous1,getMemoryUsage,enableSchedule,asynchronous2,schedule"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=4", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

Annotate the [hotspot file=4]`SystemConcurrency` class with the [hotspot=annotateManagedScheduledExecutor file=4]`@ManagedScheduledExecutorDefinition` annotation to provide a managed executor instance that enumerates the `WithVirtualThreads` required qualifiers through the [hotspot=managedScheduledExecutorService file=4]`ManagedScheduledExecutorService` injection point.

// TODO: replace the javadoc link to jakartaee11
The `@ManagedScheduledExecutorDefinition` annotation and the `ManagedScheduledExecutorService` interface are used in this bean instead of `@ManagedScheduledDefinition` annotation and `ManagedExecutorService` interface because you will implement a scheduled task in the following sections. For more information about these annotations and classes, see the Javadoc for https://openliberty.io/docs/latest/reference/javadoc/liberty-jakartaee10-javadoc.html?path=liberty-jakartaee10-javadoc/jakarta/enterprise/concurrent/package-summary.html[jakarta.enterprise.concurrent^].


Use the [hotspot=virtualManagedExecutor hotspot=submit file=4]`virtualManagedExecutor` instance to submit callable tasks that call the `getSystemPropertyTask()` method to collect different property values in parallel. Each task creates a virtual thread and returns a `Future<String>` object.

Perform a [hotspot=collect file=4]`collect()` mutable reduction operation on the entries of the [hotspot=properties file=4]`properties` map. In the operation, use the [hotspot=get file=4]`get()` method to wait for all threads to complete and to collect the results.

You started the Open Liberty in dev mode at the beginning of this section, so all the changes are automatically picked up.

Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes a second to get the result.


== Creating asynchronous tasks

Implement asynchronous tasks to get the current CPU load and memory usage.

// file 0
SystemConcurrency.java
[source,Java,linenums,role="code_column hide_tags=copyright,enableSchedule,asynchronous2,schedule"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

// file 1
persistence.xml
[source,xml,linenums,role="code_column hide_tags=copyright,schedule,schedulToggle"]
----
include::finish/src/main/resources/META-INF/persistence.xml[]
----

The [hotspot=getCpuLoad file=0]`getCpuLoad()` method uses the [hotspot=scheduleCall file=0]`virtualManagedExecutor` service to create and schedule an asynchronous task that delays the execution with [hotspot=scheduleCall hotspot=after file=0]`5` seconds. The task calculates the [hotspot=calculateCPULoad file=0]`cpuLoadData` CPU load. Then, it calls the [hotspot=persistCPULoad file=0]`persist()` method to persist the data into the database through the [hotspot=entityManager file=0]`EntityManager` interface that interacts with the [hotspot=jpa-unit file=1]`jpa-unit` persistence context in the Liberty runtime.

A transaction is required on a cascading PERSIST operation. Inside the asynchronous thread, retrieve the named [hotspot=userTransaction file=0]`UserTransaction` object from the Liberty runtime. Then, call the [hotspot=userTransaction hotspot=utBegin file=0]`begin()` method to create a transaction and call the [hotspot=userTransaction hotspot=utCommit file=0]`commit()` method to complete the transaction.

An alternative to create a similar asynchronous task is using `@Asynchronous` annotation. The [hotspot=getMemoryUsage file=0]`getMemoryUsage()` method is annotated with the [hotspot=asynchronous1 file=0]`@Asynchronous` annotation to make it running asynchronously. The task calculates the [hotspot=calculateMemoryUsage file=0]`memoryUsageData` memory usage and calls the [hotspot=persistMemoryUsage file=0]`persist()` method to persist the data into the database. To create a new transaction, annotate the `getMemoryUsage()` method by the [hotspot=transactional1 file=0]`@Transactional` annotation.

// file 2
SystemResource.java
[source,Java,linenums,role="code_column hide_tags=copyright,schedule,schedulToggle"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `SystemResource.java` file.#
`src/main/java/io/openliberty/guides/system/SystemResource.java`
----

The GET [hotspot=getCpuLoad file=2]`/systemLoad/cpuLoad` endpoint calls the `getCpuLoad()` asynchronous method and returns a message. The GET [hotspot=getMemoryUsage file=2]`/systemLoad/memoryUsage` endpoint calls the `getMemoryUsage()` asynchronous method and returns a message.

Try out the http://localhost:9080/api/system/systemLoad/cpuLoad and http://localhost:9080/api/system/systemLoad/memoryUsage URLs. Both requests return to you immediately with a message.

To check the system loads after 5 seconds, go to the http://localhost:9080/api/system/systemLoad URL.

[role="no_copy"]
----
[
  {
    "id": 1,
    "time": "2025-05-06T15:30:06.308192",
    "cpuLoad": 5.074851387343854e-06
  },
  {
    "id": 2,
    "time": "2025-05-06T15:30:08.732892",
    "memoryUsage": 0.7126722484827042
  }
]
----



== Scheduling asynchronous task

Implement a schedule task to get the current system load for every 10 seconds.

// file 0
SystemConcurrency.java
[source,Java,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

Similarly, the [hotspot=schedule file=0]`schedule()` method calculates the [hotspot=calculateSystemLoad file=0]`systemLoadData` system load data and calls the [hotspot=persistSystemLoad file=0]`persist()` method to persist the data into the database. To create a new transaction, annotate the `schedule()` method by the [hotspot=transactional2 hotspot=completableFuture file=0]`@Transactional` annotation.


Annotate the [hotspot=asynchronous2 hotspot=completableFuture file=0]`schedule()` method with the `@Asynchronous` annotation. Configure the schedule with the [hotspot=asynchronous2 file=0]`"*/10 * * * * *"` cron expression to make it running asynchronously in every 10 seconds. Return a [hotspot=returnNull file=0]`null` value to make the schedule to keep running.

To stop the schedule, return a [hotspot=completableFuture hotspot=returnCompletableFuture file=0]`CompletableFuture<>` object or raises an exception.

// file 1
SystemResource.java
[source,Java,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource.java` file.#
`src/main/java/io/openliberty/guides/system/SystemResource.java`
----

Create the GET [hotspot=schedulToggle file=1]`/schedule/toggle` endpoint that calls the `schedule()` scheduled asynchronous method.

Go to the http://localhost:9080/api/system/schedule/toggle URL to enable the schedule. After 10 seconds, go to the http://localhost:9080/api/system/systemLoad URL to check out the system loads.

[role="no_copy"]
----
[
  ...
  {
    "id": 3,
    "time": "2025-05-06T15:34:30.001636",
    "cpuLoad": 1.8270538029075587e-06,
    "memoryUsage": 0.6712260656058788
  },
  ...
]
----

After you are finished checking out the schedule, go to the http://localhost:9080/api/system/schedule/toggle URL again to disable the schedule.



== Testing the application

Although you can test your application manually, automated tests make sure consistent code quality by triggering a failure whenever a code change introduces a defect. Now, create integration tests for the endpoints.


SystemEndpointIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointIT.java` file.#
`src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java`
----

The [hotspot=testGetProperties file=0]`testGetProperties()` tests the GET `/api/system/properties/os` endpoint and confirms that 4 `os.*` properties are returned.

The [hotspot=testGetCpuLoad file=0]`testGetCpuLoad()` tests the GET `/api/system/systemLoad/cpuLoad` endpoint and confirms that the CPU load is not null after several seconds.

The [hotspot=testGetMemoryUsage file=0]`testGetMemoryUsage()` tests the GET `/api/system/systemLoad/memoryUsage` endpoint and confirms that the memory usage is not null after several seconds.

The [hotspot=testEnableSchedule file=0]`testEnableSchedule()` tests the GET `/api/systems/schedule/toggle` endpoint and confirms that 2 system loads are recorded after 21 seconds.

// =================================================================================================
// Running the tests
// =================================================================================================

[role='command']
include::{common-includes}/devmode-test.adoc[]

If the tests pass, you see an output similar to the following example:

[source, role='no_copy']
----
Running it.io.openliberty.guides.system.SystemEndpointIT
[INFO    ] Getting the os.arch property...
[INFO    ] Getting the os.version property...
[INFO    ] Getting the os.encoding property...
[INFO    ] Getting the os.name property...
...
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 57.06 s -- in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

[role='command']
include::{common-includes}/devmode-quit.adoc[]

To learn more about asynchronous and reactive programming, check out the https://openliberty.io/guides/?search=reactive[related reactive guides^].


== Great work! You're done!

You just developed tasks that run concurrently or asynchronously in a Java microservice by using Jakarta Concurrency in Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
