// Copyright (c) 2025 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: jakarta-concurrency
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2025-06-30
:page-description: Learn how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency.
:guide-author: Open Liberty
:page-tags: ['jakarta-ee']
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-related-guides: ['reactive-rest-client', 'microprofile-rest-client-async, 'reactive-messaging-sse']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Running tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency APIs
:page-seo-description: A getting started tutorial with examples on how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency APIs.
= Running tasks parallelly or asynchronously in Java microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to run tasks parallelly or asynchronously in Java microservices by using Jakarta Concurrency.

== What you'll learn

Jakarta Concurrency enables the creation of managed executors to run concurrent and asynchronous tasks in different threads. It also enables the creation of managed thread factories to create threads that run with the thread context of the component that looks up the managed thread factory. The threads are managed by the application server, coexist, and safely interact in the Enterprise Java Beans and Web containers. To learn more about Jakarta Concurrency, see the https://jakarta.ee/specifications/concurrency[Jakarta Concurrency specification^].

The application that you'll build is a dynamic web application by using Jakarta Concurrency, Jakarta RESTful Web Services, and Server-Sent Events. The front-end files are provided for you. You'll enhance it to learn how to run tasks in parallel by enhancing the GET `/api/system/properties/{prefix}` endpoint. You'll create an asynchronous task by implementing the GET `/api/system/systemLoad/{after}` endpoint that calculates the system load and broadcast it to clients after the provided `{after}` seconds. Also, you'll learn how to create a scheduled asynchronous task that retrieves and broadcasts the current system load for every 10 seconds.


// =================================================================================================
// Getting started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Go to the http://localhost:9080/api/system/properties/os URL to see all the `os.*` properties. You will see an output similar to the following:

[role="no_copy"]
----
{
  "os.arch": "aarch64",
  "os.name": "Mac OS X",
  "os.version": "15.4.1",
  "os.encoding": "UTF-8"
}
----

If you interest, you can check out the endpoint by the http://localhost:9080/api/system/properties/user and http://localhost:9080/api/system/properties/java URLs.

Check out the web application at the http://localhost:9080 URL. Click the image:refresh.svg[refresh icon, 20, 20] refresh button, located in the table title, to update and display the current system load in the table after 5 seconds.

Click the image:schedule.svg[schedule icon, 20, 20] schedule button to toggle the schedule that posts the current system load in every 10 seconds.

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Running tasks in parallel

Navigate to the `start` directory to begin.
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-jakarta-concurrency/start
```
endif::[]

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

// file 0
SystemResource.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

// file 1
start/SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

// file 2
server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The starting application is implemented the [hotspot=getProperties file=0]`/properties/{prefix}` endpoint. Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes several seconds to get the result. Each [hotspot=doSomethingSleep hotspot=getSystemPropertyTask hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` call takes at most a second.

To improve the performance, enhance the [hotspot=getProperties file=1]`getProperties()` method to call the [hotspot=callGetSystemPropertyTask file=1]`getSystemPropertyTask()` method in parallel.

// TODO: replace the concurrent-3.0.html to concurrent-3.1.html
The https://openliberty.io/docs/latest/reference/feature/concurrent-3.0.html[Jakarta Concurrency^] feature is enabled for you in the Liberty [hotspot=concurrent file=2]`server.xml` configuration file.

// file 3
WithVirtualThreads.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/WithVirtualThreads.java[]
----

[role="code_command hotspot file=3", subs="quotes"]
----
#Create the `WithVirtualThreads.java` file.#
`src/main/java/io/openliberty/guides/system/WithVirtualThreads.java`
----

The [hotspot file=3]`WithVirtualThreads` qualifier annotation class is used to enumerate the required qualifiers for the managed executor service.

The managed executor service provides a way to start asynchronous tasks within an application server environment. It propagates various thread contexts that are relevant to Jakarta EE applications.

// file 4
SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright,subscribe,calculateSystemLoad,asynchronous1,getSystemLoad,enableSchedule,asynchronous2,schedule"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=4", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

Annotate the [hotspot file=4]`SystemConcurrency` class with the [hotspot=annotateManagedScheduledExecutor file=4]`@ManagedScheduledExecutorDefinition` annotation to provide a managed executor instance that enumerates the `WithVirtualThreads` required qualifiers through the [hotspot=managedScheduledExecutorService file=4]`ManagedScheduledExecutorService` injection point. Set the [hotspot=virtual file=4]`virtual` attribute to true to use virtual thread.

// TODO: replace the javadoc link to jakartaee11
The `@ManagedScheduledExecutorDefinition` annotation and the `ManagedScheduledExecutorService` interface are used in this guide instead of `@ManagedScheduledDefinition` annotation and `ManagedExecutorService` interface, because you will implement a scheduled task in the following sections. For more information about these annotations and classes, see the Javadocs for https://openliberty.io/docs/latest/reference/javadoc/liberty-jakartaee10-javadoc.html?path=liberty-jakartaee10-javadoc/jakarta/enterprise/concurrent/package-summary.html[jakarta.enterprise.concurrent^].


Use the [hotspot=virtualManagedExecutor hotspot=submit file=4]`virtualManagedExecutor` instance to submit callable tasks that call the `getSystemPropertyTask()` method to collect different property values parallelly. Each task creates a virtual thread and returns a `Future<String>` object.

Perform a [hotspot=collect file=4]`collect()` mutable reduction operation on the entries of the [hotspot=properties file=4]`properties` map. In the operation, use the [hotspot=get file=4]`get()` method to wait for all threads to complete and to collect the results.

You started the Open Liberty in dev mode at the beginning of this section, so all the changes were automatically picked up.

Go to the http://localhost:9080/api/system/properties/java URL to see all the `java.*` properties. Notice that the URL takes a second to get the result.

== Creating asynchronous task

Implement an asynchronous task to get the current system load that includes the CPU and memory usages.

// file 0
SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright,enableSchedule,asynchronous2,schedule"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

// file 1
SseService.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::start/src/main/java/io/openliberty/guides/system/SseService.java[]
----

The [hotspot=getSystemLoad file=0]`getSystemLoad()` method uses the [hotspot=scheduleCall file=0]`virtualManagedExecutor` service to schedule a task that will be delayed with the given [hotspot=parameters hotspot=after file=0]`after` seconds. The task calls the [hotspot=calculateSystemLoad hotspot=callCalculateSystemLoad1 file=0]`calculateSystemLoad()` method to calculate the CPU and memory usage and then the [hotspot=broadcast1 file=0]`broadcasts()` method to broadcast the system load to clients through the [hotspot file=1]`SseService` bean that is provided for you. 

Annotate the [hotspot=asynchronous1 hotspot=parameters file=0]`getSystemLoad()` method with the `@Asynchronous` annotation to make it running asynchronously.

// file 2
SystemResource.java
[source,xml,linenums,role="code_column hide_tags=copyright,schedule,schedulToggle"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `SystemResource.java` file.#
`src/main/java/io/openliberty/guides/system/SystemResource.java`
----

Create the GET [hotspot=getSystemLoad file=2]`/systemLoad/{after}` endpoint that calls the above  `getSystemLoad()` asynchronous method and returns a message.

Try out the http://localhost:9080/api/system/systemLoad/5 URL. The request returns to you immediatedly with the message.

// file 3
index.html
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/index.html[]
----

// file 4
index.js
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/index.js[]
----

To see the system load, check out the web application at the http://localhost:9080 URL. Click the image:refresh.svg[refresh icon, 20, 20] refresh button that calls the [hotspot=refreshButton file=3]`refreshCall()` method. The [hotspot=refreshCall file=4]`refreshCall()` method calls the `/api/system/systemLoad/5` endpoint.

After 5 seconds, you'll see that the current system load is added at the first row of the table.


== Scheduling asynchronous task

Implement a schedule task to get the current system load for every 10 seconds.

// file 0
SystemConcurrency.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemConcurrency.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemConcurrency.java` file.#
`src/main/java/io/openliberty/guides/system/SystemConcurrency.java`
----

Similarly, the [hotspot=schedule file=0]`schedule()` method calls the [hotspot=calculateSystemLoad hotspot=callCalculateSystemLoad2 file=0]`calculateSystemLoad()` method to calculate the CPU and memory usage and then the [hotspot=broadcast2 file=0]`broadcasts()` method to broadcast the system load to clients.

Annotate the [hotspot=asynchronous2 hotspot=completableFuture file=0]`schedule()` method with the `@Asynchronous` annotation. Configue the schedule with the [hotspot=asynchronous2 file=0]`"*/10 * * * * *"` cron expression to make it running asynchronously in every 10 seconds. Return a [hotspot=returnNull file=0]`null` value to let the schedule to keep running.

To stop the scheulde, return a [hotspot=completableFuture hotspot=returnCompletableFuture file=0]`CompletableFuture<>` object or raises an exception.

// file 1
SystemResource.java
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource.java` file.#
`src/main/java/io/openliberty/guides/system/SystemResource.java`
----

Create the GET [hotspot=schedulToggle file=1]`/schedule/toggle` endpoint that calls the above `schedule()` scheduled asynchronous method.

// file 2
index.html
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/index.html[]
----

// file 3
index.js
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/index.js[]
----

Check out the web application at the http://localhost:9080 URL. Click the image:schedule.svg[schedule icon, 20, 20] schedule button to toggle the schedule that posts the current system load in every 10 seconds. The button calls the [hotspot=scheduleButton file=2]`scheduleCall()` method. The [hotspot=scheduleCall file=3]`scheduleCall()` method calls the `/api/system/schedule/toggle` endpoint.

You'll see that the current system load is added at the first row of the table in every 10 seconds.

After you are finished checking out the schedule, click the image:schedule.svg[schedule icon, 20, 20] schedule button again to stop the schedule.


== Testing the application

Although you can test your application manually, automated tests make sure consistent code quality by triggering a failure whenever a code change introduces a defect. Now, create integration tests for the endpoints.


SystemEndpointIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointIT.java` file.#
`src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java`
----

The [hotspot=testGetProperties file=0]`testGetProperties()` tests the GET `/api/system/properties/os` endpoint and confirms that there are 4 `os.*` properties.

The [hotspot=testGetSystemLoad file=0]`testGetSystemLoad()` tests the GET `/api/system/systemLoad/5` endpoint and confirms that the CPU and memory usages are not null after 10 seconds.

The [hotspot=testEnableSchedule file=0]`testEnableSchedule()` tests the GET `/api/systems/schedule/toggle` endpoint and confirms that there are 3 system loads after 35 seconds.

// =================================================================================================
// Running the tests
// =================================================================================================

[role='command']
include::{common-includes}/devmode-test.adoc[]

If the tests pass, you see a similar output to the following example:

[source, role='no_copy']
----
Running it.io.openliberty.guides.system.SystemEndpointIT
[INFO    ] Getting the os.arch property...
[INFO    ] Getting the os.version property...
[INFO    ] Getting the os.encoding property...
[INFO    ] Getting the os.name property...
...
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 55.42 s -- in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

[role='command']
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You just developed tasks that run parallelly or asynchronously in a Java microservice by using Jakarta Concurrency in Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
